repos:
  # Only include minimal, non-intrusive checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: debug-statements

  # Use local flake8 with your relaxed configuration
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [--config=.flake8]
        
  # Skip black, isort, mypy, and bandit to avoid source code changes
  # Comment out these sections if you want to enforce them later
  
  # - repo: https://github.com/psf/black
  #   rev: 23.7.0
  #   hooks:
  #     - id: black
  #       language_version: python3.12
  #       args: [--line-length=100]

  # - repo: https://github.com/pycqa/isort
  #   rev: 5.12.0
  #   hooks:
  #     - id: isort
  #       args: ["--profile", "black", "--line-length", "100"]

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.4.1
  #   hooks:
  #     - id: mypy
  #       additional_dependencies: [types-requests, types-PyYAML]
  #       args: [--ignore-missing-imports]

  # - repo: https://github.com/pycqa/bandit
  #   rev: 1.7.5
  #   hooks:
  #     - id: bandit
  #       args: ["-c", "pyproject.toml"]
  #       additional_dependencies: ["bandit[toml]"]